// Code generated by mockery v2.14.0. DO NOT EDIT.

package database

import mock "github.com/stretchr/testify/mock"

// MockIPersistence is an autogenerated mock type for the IPersistence type
type MockIPersistence struct {
	mock.Mock
}

// Exec provides a mock function with given fields: sqlQuery, params
func (_m *MockIPersistence) Exec(sqlQuery string, params ...interface{}) error {
	ret := _m.Called(sqlQuery, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(sqlQuery, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Select provides a mock function with given fields: dest, sqlQuery, params
func (_m *MockIPersistence) Select(dest interface{}, sqlQuery string, params ...interface{}) error {
	ret := _m.Called(dest, sqlQuery, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = rf(dest, sqlQuery, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockIPersistence interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIPersistence creates a new instance of MockIPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIPersistence(t mockConstructorTestingTNewMockIPersistence) *MockIPersistence {
	mock := &MockIPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
